[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
sql        = { path = "../sql" }
lsm        = { path = "../lsm" }
thiserror  = { workspace = true }
tokio      = { workspace = true }
parking_lot = { workspace = true }
tracing    = { workspace = true }
uuid       = { workspace = true }
