// Auto-generated by flutter_rust_bridge_codegen.
// This stub is overwritten by `flutter_rust_bridge_codegen generate` in CI.
// Keeping it empty here lets `cargo build` succeed before codegen has run.
